#!/bin/python3

import math
import os
import random
import re
import sys



#
# Complete the 'quickSort' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def quickSort(arr):
    # Write your code here
    pivot=arr[0]
    left=[]
    right=[]
    middle=[]
    for i in range(n):
        if(arr[i]>pivot):
            right.append(arr[i])
        if(arr[i]<pivot):
             left.append(arr[i])
        if(arr[i]==pivot):
             middle.append(arr[i])
    return left+middle+right
   

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = quickSort(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
